/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project2.hibernate.swing;

import com.project2.hibernate.controllers.EmployeController;
import javax.swing.JOptionPane;

/**
 *
 * @author Hendrilalaina
 */
@SuppressWarnings("serial")
public class AjouterEmployeDialog extends javax.swing.JDialog {

    /**
     * Creates new form AjouterEmployeDialog
     */
    public AjouterEmployeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomAjouterEmploye = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prenomAjouterEmploye = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        posteAjouterEmploye = new javax.swing.JTextField();
        ajouterBoutonAjouterEmploye = new javax.swing.JButton();
        annulerAjouterEmploye = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel3.setText("Poste :");

        ajouterBoutonAjouterEmploye.setText("Ajouter");
        ajouterBoutonAjouterEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBoutonAjouterEmployeActionPerformed(evt);
            }
        });

        annulerAjouterEmploye.setText("Annuler");
        annulerAjouterEmploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerAjouterEmployeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomAjouterEmploye)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(prenomAjouterEmploye)
                            .addComponent(posteAjouterEmploye))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(ajouterBoutonAjouterEmploye)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annulerAjouterEmploye)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomAjouterEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenomAjouterEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posteAjouterEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterBoutonAjouterEmploye)
                    .addComponent(annulerAjouterEmploye))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterBoutonAjouterEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBoutonAjouterEmployeActionPerformed
        // TODO add your handling code here:
        String nom = nomAjouterEmploye.getText();
        String prenom = prenomAjouterEmploye.getText();
        String poste = posteAjouterEmploye.getText();
        if(!nom.equals("") && !prenom.equals("") && !poste.equals("")){
            EmployeController employeController = new EmployeController();
            try{
                employeController.ajouter(nom, prenom, poste);
                this.setVisible(false);
                JOptionPane.showMessageDialog(this.getParent(), "L'employé est ajouté");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Une erreur s'est produite!", "Error",HEIGHT);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Compléter tous les champs!");
        }        
    }//GEN-LAST:event_ajouterBoutonAjouterEmployeActionPerformed

    private void annulerAjouterEmployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerAjouterEmployeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_annulerAjouterEmployeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBoutonAjouterEmploye;
    private javax.swing.JButton annulerAjouterEmploye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomAjouterEmploye;
    private javax.swing.JTextField posteAjouterEmploye;
    private javax.swing.JTextField prenomAjouterEmploye;
    // End of variables declaration//GEN-END:variables
}
