/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project2.hibernate.swing;

import java.time.ZoneId;
import java.util.Date;
import java.util.List;

import com.project2.hibernate.controllers.AffecterController;
import com.project2.hibernate.controllers.EmployeController;
import com.project2.hibernate.controllers.LieuController;
import com.project2.hibernate.models.Employe;
import com.project2.hibernate.models.Lieu;
import javax.swing.JOptionPane;

/**
 *
 * @author Hendrilalaina
 */
@SuppressWarnings("serial")
public class AjouterAffecterDialog extends javax.swing.JDialog {

    /**
     * Creates new form AjouterA
     * ffecterDialog
     */
    public AjouterAffecterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadComboBox();
    }
    
    public void loadComboBox() {
    	EmployeController employeController = new EmployeController();
    	LieuController lieuController = new LieuController();
    	
    	List<Employe> employes = employeController.lister();
    	List<Lieu> lieux = lieuController.lister();
    	codeEmployeComboAjouterAffecter.removeAllItems();
        codeEmployeComboAjouterAffecter.addItem("");
    	for (Employe employe : employes) {
    		codeEmployeComboAjouterAffecter.addItem(employe.getCodeEmp());
    	}
    	codeLieuComboAjouterAffecter.removeAllItems();
        codeLieuComboAjouterAffecter.addItem("");
    	for (Lieu lieu : lieux) {
    		codeLieuComboAjouterAffecter.addItem(lieu.getDesignation());
    	}
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codeEmployeComboAjouterAffecter = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        codeLieuComboAjouterAffecter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        dateAjouterAffecter = new com.toedter.calendar.JDateChooser();
        ajouterBoutonAjouterAffecter = new javax.swing.JButton();
        annulerBoutonAjouterAffecter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Code Employe :");

        codeEmployeComboAjouterAffecter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Code Lieu");

        codeLieuComboAjouterAffecter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Date d'affectation :");

        dateAjouterAffecter.setDateFormatString("yyyy-MM-dd");

        ajouterBoutonAjouterAffecter.setText("Ajouter");
        ajouterBoutonAjouterAffecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterBoutonAjouterAffecterActionPerformed(evt);
            }
        });

        annulerBoutonAjouterAffecter.setText("Annuler");
        annulerBoutonAjouterAffecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerBoutonAjouterAffecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeEmployeComboAjouterAffecter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(codeLieuComboAjouterAffecter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateAjouterAffecter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(ajouterBoutonAjouterAffecter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(annulerBoutonAjouterAffecter)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeEmployeComboAjouterAffecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeLieuComboAjouterAffecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAjouterAffecter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouterBoutonAjouterAffecter)
                    .addComponent(annulerBoutonAjouterAffecter))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerBoutonAjouterAffecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerBoutonAjouterAffecterActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_annulerBoutonAjouterAffecterActionPerformed

	private void ajouterBoutonAjouterAffecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterBoutonAjouterAffecterActionPerformed
            String codeEmploye = (String) codeEmployeComboAjouterAffecter.getSelectedItem();
            String designation = (String) codeLieuComboAjouterAffecter.getSelectedItem();
            Lieu lieu = new LieuController().lieuByDesignation(designation);
            Date date = dateAjouterAffecter.getDate();
       
            if (!codeEmploye.equals("") && !designation.equals("") && !date.toString().equals("")) {
                AffecterController affecterController = new AffecterController();
                try {
                    affecterController.ajouter(codeEmploye, lieu.getCodeLieu(), date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(this.getParent(), "L'affectaion est ajoutée.");
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "L'affectation est déjà existée!", "Error",HEIGHT);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Compléter tous les champs!");
            }
        
    }//GEN-LAST:event_ajouterBoutonAjouterAffecterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterBoutonAjouterAffecter;
    private javax.swing.JButton annulerBoutonAjouterAffecter;
    private javax.swing.JComboBox<String> codeEmployeComboAjouterAffecter;
    private javax.swing.JComboBox<String> codeLieuComboAjouterAffecter;
    private com.toedter.calendar.JDateChooser dateAjouterAffecter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
